export default {
  msg: "操作成功",
  code: 0,
  data: [
    {
      creator: "默认用户",
      'create_time': "2020-02-25 14:04:14",
      updator: "默认用户",
      'update_time': "2020-02-25 14:04:14",
      id: 1,
      'parent_id': "",
      'env_name': "测试",
      'group_name': "权限管理",
      perms: "auth",
      'resource_type': "M",
      sort: 1,
      memo: "",
      'front_url': "",
      'back_url': "",
      'icon_class': "gs-icon-manage",
      children: [
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 16,
          'parent_id': 1,
          'env_name': "测试",
          'group_name': "用户管理",
          perms: "auth:user",
          'resource_type': "M",
          sort: 1,
          memo: "",
          'front_url': "/home/userManagement",
          'back_url': "",
          'icon_class': "",
          children: []
        },
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 17,
          'parent_id': 1,
          'env_name': "测试",
          'group_name': "角色管理",
          perms: "auth:role",
          'resource_type': "M",
          sort: 2,
          memo: "",
          'front_url': "/home/roleManagement",
          'back_url': "",
          'icon_class': "",
          children: []
        }
      ]
    },
    {
      creator: "默认用户",
      'create_time': "2020-02-25 14:04:14",
      updator: "默认用户",
      'update_time': "2020-02-25 14:04:14",
      id: 2,
      'parent_id': "",
      'env_name': "测试",
      'group_name': "操作日志",
      perms: "log",
      'resource_type': "M",
      sort: 2,
      memo: "",
      'front_url': "/home/logManage",
      'back_url': "",
      'icon_class': "gs-icon-copy-o",
      children: [
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 38,
          'parent_id': 2,
          'env_name': "测试",
          'group_name': "查看",
          perms: "log:view",
          'resource_type': "O",
          sort: 1,
          memo: "",
          'front_url': "",
          'back_url': "",
          'icon_class': "",
          children: []
        }
      ]
    },
    {
      creator: "默认用户",
      'create_time': "2020-02-25 14:04:14",
      updator: "默认用户",
      'update_time': "2020-02-25 14:04:14",
      id: 5,
      'parent_id': "",
      'env_name': "测试",
      'group_name': "知识查询",
      perms: "kgs",
      'resource_type': "M",
      sort: 3,
      memo: "",
      'front_url': "/home/query",
      'back_url': "",
      'icon_class': "gs-icon-query",
      children: [
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 42,
          'parent_id': 5,
          'env_name': "测试",
          'group_name': "查看",
          perms: "kgs:view",
          'resource_type': "O",
          sort: 1,
          memo: "",
          'front_url': "",
          'back_url': "",
          'icon_class': "",
          children: []
        }
      ]
    },
    {
      creator: "默认用户",
      'create_time': "2020-02-25 14:04:14",
      updator: "默认用户",
      'update_time': "2020-02-25 14:04:14",
      id: 4,
      'parent_id': "",
      'env_name': "测试",
      'group_name': "文档处理",
      perms: "file",
      'resource_type': "M",
      sort: 4,
      memo: "",
      'front_url': "",
      'back_url': "",
      'icon_class': "gs-icon-extract",
      children: [
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 8,
          'parent_id': 4,
          'env_name': "测试",
          'group_name': "文档导入",
          perms: "file:import",
          'resource_type': "M",
          sort: 1,
          memo: "",
          'front_url': "/home/import-doc",
          'back_url': "",
          'icon_class': "",
          children: [
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 39,
              'parent_id': 8,
              'env_name': "测试",
              'group_name': "查看",
              perms: "file:import:view",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            }
          ]
        },
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 9,
          'parent_id': 4,
          'env_name': "测试",
          'group_name': "文档管理",
          perms: "file:mgr",
          'resource_type': "M",
          sort: 2,
          memo: "",
          'front_url': "/home/fileManage",
          'back_url': "",
          'icon_class': "",
          children: [
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 19,
              'parent_id': 9,
              'env_name': "测试",
              'group_name': "编辑",
              perms: "file:mgr:edit",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 20,
              'parent_id': 9,
              'env_name': "测试",
              'group_name': "删除",
              perms: "file:mgr:delete",
              'resource_type': "O",
              sort: 2,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 40,
              'parent_id': 9,
              'env_name': "测试",
              'group_name': "查看",
              perms: "file:mgr:view",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            }
          ]
        },
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 10,
          'parent_id': 4,
          'env_name': "测试",
          'group_name': "标注&抽取",
          perms: "file:brat",
          'resource_type': "M",
          sort: 3,
          memo: "",
          'front_url': "/home/extract",
          'back_url': "",
          'icon_class': "",
          children: [
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 41,
              'parent_id': 10,
              'env_name': "测试",
              'group_name': "查看",
              perms: "file:brat:view",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            }
          ]
        }
      ]
    },
    {
      creator: "默认用户",
      'create_time': "2020-02-25 14:04:14",
      updator: "默认用户",
      'update_time': "2020-02-25 14:04:14",
      id: 3,
      'parent_id': "",
      'env_name': "测试",
      'group_name': "数据库处理",
      perms: "db",
      'resource_type': "M",
      sort: 5,
      memo: "",
      'front_url': "",
      'back_url': "",
      'icon_class': "gs-icon-import",
      children: [
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 11,
          'parent_id': 3,
          'env_name': "测试",
          'group_name': "数据源配置",
          perms: "db:config",
          'resource_type': "M",
          sort: 1,
          memo: "",
          'front_url': "/home/config-db",
          'back_url': "",
          'icon_class': "",
          children: []
        },
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 12,
          'parent_id': 3,
          'env_name': "测试",
          'group_name': "映射&导入",
          perms: "db:task",
          'resource_type': "M",
          sort: 2,
          memo: "",
          'front_url': "/home/db-map-list",
          'back_url': "",
          'icon_class': "",
          children: [
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 23,
              'parent_id': 12,
              'env_name': "测试",
              'group_name': "编辑",
              perms: "db:task:edit",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 24,
              'parent_id': 12,
              'env_name': "测试",
              'group_name': "执行",
              perms: "db:task:run",
              'resource_type': "O",
              sort: 2,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 45,
              'parent_id': 12,
              'env_name': "测试",
              'group_name': "查看",
              perms: "db:view",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            }
          ]
        }
      ]
    },
    {
      creator: "默认用户",
      'create_time': "2020-02-25 14:04:14",
      updator: "默认用户",
      'update_time': "2020-02-25 14:04:14",
      id: 6,
      'parent_id': "",
      'env_name': "测试",
      'group_name': "图谱管理",
      perms: "kgm",
      'resource_type': "M",
      sort: 6,
      memo: "",
      'front_url': "",
      'back_url': "",
      'icon_class': "gs-icon-manage",
      children: [
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 13,
          'parent_id': 6,
          'env_name': "测试",
          'group_name': "本体管理",
          perms: "kgm:schema",
          'resource_type': "M",
          sort: 1,
          memo: "",
          'front_url': "/home/body-manage",
          'back_url': "",
          'icon_class': "",
          children: [
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 43,
              'parent_id': 13,
              'env_name': "测试",
              'group_name': "查看",
              perms: "kgm:schema:view",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 25,
              'parent_id': 13,
              'env_name': "测试",
              'group_name': "新增",
              perms: "kgm:schema:add",
              'resource_type': "O",
              sort: 2,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 26,
              'parent_id': 13,
              'env_name': "测试",
              'group_name': "修改",
              perms: "kgm:schema:edit",
              'resource_type': "O",
              sort: 3,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 27,
              'parent_id': 13,
              'env_name': "测试",
              'group_name': "删除",
              perms: "kgm:schema:delete",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 28,
              'parent_id': 13,
              'env_name': "测试",
              'group_name': "导入",
              perms: "kgm:schema:import",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            }
          ]
        },
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 14,
          'parent_id': 6,
          'env_name': "测试",
          'group_name': "实体管理",
          perms: "kgm:entity",
          'resource_type': "M",
          sort: 2,
          memo: "",
          'front_url': "/home/entity-manage",
          'back_url': "",
          'icon_class': "",
          children: [
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 44,
              'parent_id': 14,
              'env_name': "测试",
              'group_name': "查看",
              perms: "kgm:entity:view",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 31,
              'parent_id': 14,
              'env_name': "测试",
              'group_name': "修改",
              perms: "kgm:entity:edit",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 29,
              'parent_id': 14,
              'env_name': "测试",
              'group_name': "高级搜索",
              perms: "kgm:entity:high-search",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 30,
              'parent_id': 14,
              'env_name': "测试",
              'group_name': "新增",
              perms: "kgm:entity:add",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 32,
              'parent_id': 14,
              'env_name': "测试",
              'group_name': "删除",
              perms: "kgm:entity:delete",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 33,
              'parent_id': 14,
              'env_name': "测试",
              'group_name': "导入",
              perms: "kgm:entity:import",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            },
            {
              creator: "默认用户",
              'create_time': "2020-02-25 14:04:14",
              updator: "默认用户",
              'update_time': "2020-02-25 14:04:14",
              id: 34,
              'parent_id': 14,
              'env_name': "测试",
              'group_name': "Cypher查询",
              perms: "kgm:entity:cypher-search",
              'resource_type': "O",
              sort: 1,
              memo: "",
              'front_url': "",
              'back_url': "",
              'icon_class': "",
              children: []
            }
          ]
        }
      ]
    },
    {
      creator: "默认用户",
      'create_time': "2020-02-25 14:04:14",
      updator: "默认用户",
      'update_time': "2020-02-25 14:04:14",
      id: 7,
      'parent_id': "",
      'env_name': "测试",
      'group_name': "知识应用",
      perms: "kga",
      'resource_type': "M",
      sort: 7,
      memo: "",
      'front_url': "",
      'back_url': "",
      'icon_class': "gs-icon-using",
      children: [
        {
          creator: "默认用户",
          'create_time': "2020-02-25 14:04:14",
          updator: "默认用户",
          'update_time': "2020-02-25 14:04:14",
          id: 15,
          'parent_id': 7,
          'env_name': "测试",
          'group_name': "图谱分析",
          perms: "kga:chart",
          'resource_type': "M",
          sort: 1,
          memo: "",
          'front_url': "/home/graphAnalysis",
          'back_url': "",
          'icon_class': "",
          children: []
        }
      ]
    }
  ]
}
